server:
  port: 8080
  tomcat:
    connection-timeout: 20000

spring:
  datasource:
    # default url is localhost:3306
    # name of created database
    # username is root by default
    # password you enter to connect to 127.0.0.1:3306
    url: jdbc:mysql://[your_local_host]/[database_name]
    username: [username]
    password: [password]
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          storage_engine: InnoDB
  thymeleaf:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092

minio:
  # create a minio account and input your username in the access key section as well as password into the secret key section.
  # endpoint for minio console. default is http://127.0.0.1:9000/
  # insert your bucket name so minio will upload files into it if exists, otherwise it creates a new bucket for storage.
  access_key:
  secret_key:
  end_point:
  bucket_name:

# create an account on openai to get the api key
# you can get the base url from the official documentation of openai
# specify the pathname to save your files to be logged into object storage server (minio bucket)
# specify the kafka topic name, so you can log your data into that topic if exists, otherwise kafka will create a new topic with that name to log your records
openai:
  api_key:
  url: https://api.openai.com/v1/
  chat_completion_model: gpt-3.5-turbo
  transcription_model: whisper-1
  text_speech_model: tts-1
  pathname:
  topic_name: